
# 更多参数详情，请查阅
# https://help.github.com/cn/actions
# https://p3terx.com/archives/github-actions-started-tutorial.html
# http://www.ruanyifeng.com/blog/2019/09/getting-started-with-github-actions.html

name: Github Action Build and Deploy  #工作流的名称，随便定义

# 触发工作流的事件
# 下面设置的是当 push 到 master 分支后触发
# 其它事件还有 pull_request | page_build | release | ...
# https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches:
      - master

# Jobs 即工作流中的执行任务
jobs:
  build:                              #Job_id 名称为 build，自主定义
    #name: Deploy webiste             #name 是 job_id 的说明，省略后的 name 值，会默认为 Job_id 的值
    runs-on: ubuntu-latest            #设置虚拟服务器环境（ubuntu最新版本）

    # 任务步骤集合
    steps:
      - name: Pull Code               #Action 名称，自主定义
        uses: actions/checkout@v2     #使用 Github Action 官方可重用的脚本，actions/checkout 获取源码
                                      #@ 后面可指定分支、release 版本或特定的 commit
                                      #https://help.github.com/cn/actions/building-actions/about-actions#versioning-your-action
        # with:                       #当前 actions 的一些配置
        #   submodules: true          #项目内有 Git 子项目时可以设为 true，拉取的时候会一并拉取下来

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"        #设置要安装的 Node 版本

      - name: NPM Install Packges     #设置 npm 要执行的步骤，当成本地操作就行
        # run: npm install            #run 可设置执行的命令，一个 step 直接写，多个按照下方格式写
        run: |
          npm install hexo-cli -g
          npm install
          hexo clean
          hexo generate

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_ACTION_TEST_KEY }} #在 Settings/Secrets 内设置的 token 名称
                                                          #未创建个人Token的，请换成${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages            #要部署到哪个分支
          FOLDER: public              #从那个文件夹内复制静态文件
          COMMIT_NAME: "Github Pages Deploy Action"

  # 以下是 Jobs 的执行顺序说明
  # 不要复制
  # -------------------------------------------
  # jobs2:
  #   needs: build
  # job3:
  #   needs: [build, jobs2]
  # -------------------------------------------
  # 多个任务时，使用 needs 排列执行顺序，否则同时运行
