name: deploying Hexo project to GitHub pages

on:
  push:
    branches:
      - master

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HEXO_DEPLOY }}
          publish_dir: ./public
          publish_branch: gh-pages